services:
  next-app:
    container_name: next-app
    build:
      context: ./next
      dockerfile: ../nodejs/Dockerfile
    ports:
      - "3030:3000"
    volumes:
      - ./next:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    tty: true
    
  nuxt-app:
    container_name: nuxt-app
    build:
      context: ./nuxt
      dockerfile: ../nodejs/Dockerfile
    ports:
      - "3031:3000"
    volumes:
      - ./nuxt:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.nuxt
      - /usr/src/app/.output
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    tty: true

  db:
    image: mysql:8.4
    container_name: ITSeminar_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itSeminardb
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3308:3306"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      

